### ISSUE TITLE
crash during render

### ISSUE THREAD

**Issue by Papirosnik** [igagis/svgren#37]
Hi there!
I've updated to 0.4.42 because of performance issue on our nice sport car.
Greats improvements! Car is rendered about 20 times faster!!!
Then I tried  other (previously hard-rendered) svgs and alas... some of them crash
[machupicchu.zip](https://github.com/igagis/svgren/files/1433720/machupicchu.zip)
.
Could you please locate and fix a problem?
Thanks in advance!

**Comment by igagis** [comment]
Yep, I will have a look.

**Comment by igagis** [comment]
The crash is fixed in **svgren 0.4.43**. Should be there soon:
https://ci.appveyor.com/project/igagis/svgren/build/master-443
https://travis-ci.org/igagis/svgren/builds/295725050

But I also noticed that these 4 images that you attached are rendererd differently by different software. I tried Firefox, Chrome, Internet Explorer, svgren. All these give different results at least for images 04 and 06. I suspect that IE does the best job. svgren is close to right result. Worst one was Chrome.
So, in relation to this, could you create a separate issue and attach raster images of how those are expected to look, if you find that svgren does not render something correctly?

**Comment by Papirosnik** [comment]
I beg your pardon )
those svgs are wrong exported.
I think they cannot be considered as samples.

**Comment by igagis** [comment]
Hm, ok. But the crash should be fixed now.
