### ISSUE TITLE
Does your library support SVG manipulating?

### ISSUE THREAD

**Issue by Nizarazo** [igagis/svgren#73]
Meaning user can click on SVG object and it will respond such as rotating or moving ?

**Comment by igagis** [comment]
Nope, this is not supported. Only rendering of static images.

**Comment by Nizarazo** [comment]
Thank you for your response.
Do you know C++ tool that can manipulate SVG?
or a tool that can parse and manipulate SVG?

**Comment by igagis** [comment]
There is a number of SVG document libraries out there, including my own `svgdom`, you can find it here on github. I cannot say anything about other libs, I have not played with them.

**Comment by Nizarazo** [comment]
Thank you for your response.
Is it possible by using both your svgdom and svgren to click on SVG object and it will respond?meaning it will rotate or move?
In other words I need to register the SVG object to respond for events such as mouse down or keydown?

**Comment by igagis** [comment]
in theory it is possible, but the implementation will not be trivial.

**Comment by Nizarazo** [comment]
Any examples available demonstrating how to do it by using your svgdom and svgren?

**Comment by igagis** [comment]
Unfortunately, there are no such examples. As I said, the implementation of that functionality will not be trivial, because this is not something which was kept in mind when the libraries were designed.
In order to implement that one has to do own click detection by traversing the SVG DOM and then by modifying the SVG DOM accordingly react on the detected mouse click.
I know that @JaimeIvanCervantes was doing something like this in his project, maybe he could describe how he achieved similar functionality and how much efforts it took.
